config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :profiles, only: [:show] do
    get '/cars', to: 'cars#current_user_cars', as: :cars
  end


  resources :cars do
    resources :rentals, only: [:new, :create]
    get '/rentals', to: 'rentals#current_car_rentals'
    resources :reviews, only: [:index, :show]
  end

  resources :rentals, only: [:index, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
  end


  # resources :reviews, only: [:index, :show]

    # resources :rentals, only: [:index, :new, :create, :show, :destroy] do
      # resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
  end

end

# when policies setup

    # if policy(profile).show?
    # else
    #   redirect_to root_path
    # end


# policies profile

# def show?
#   current_user == User.find(params[:id])
# end

app/views/profiles/shared/_car_card.html.erb
<div class="card profile-car-card shadow">
  <%= cl_image_tag car.photo.key, crop: :fill, class: 'card-img-top' %>
  <div class="card-footer d-flex justify-content-between align-items-top">
    <%= car.model %>
    <div class="icons d-flex justify-content-between">
      <p class="mb-0">
        <a data-toggle="collapse" href="#multiCollapseExample-<%= car.id %>" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">
          <i class="far fa-comment-alt mr-3"></i>
        </a>
      </p>
      <p class="mb-0">
        <%= link_to edit_car_path(car), class: 'text-decoration-none' do  %>
          <i class="far fa-edit mr-3"></i>
        <% end %>
      </p>
      <p class="mb-0">
        <%= link_to car_path(car), method: :delete, data: { confirm: "Are you sure?" }, class: 'text-decoration-none' do  %>
          <i class="fas fa-times-circle"></i>
        <% end %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="collapse multi-collapse" id="multiCollapseExample-<%= car.id %>">
        <div class="card card-body">
          <% if car.renter_reviews.empty? %>
            No reviews yet
          <% end %>
          <% car.renter_reviews.each do |review| %>
            <div class="profile-car-review d-flex justify-content-between px-2 pt-2 mb-2">
              <div class="rating-user d-flex flex-column">
                <div class="stars d-flex justify-content-between mb-3" style="width: 20%;">
                  <% review.rating.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                  <% (5 - review.rating).times do %>
                    <i class="far fa-star"></i>
                  <% end %>
                </div>
                <p class="font-italic">From <%= review.rental.user.username.capitalize %></p>
              </div>
              <%= cl_image_tag review.rental.user.photo.key, crop: :fill, class: 'profile-avatar'  %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/shared/_review_card.html.erb
<div class="card mt-4 reviewcard p-4">
  <div class="d-flex justify-content-between">
    <div class="card-body p-0">
      <div class="first-line d-flex justify-content-between">
        <div class="stars d-flex justify-content-between mb-3" style="width: 20%;">
          <% review.rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - review.rating).times do %>
            <i class="far fa-star"></i>
          <% end %>
        </div>
        <%= link_to rentals_path, class: 'text-decoration-none' do  %>
          <i class="fas fa-info-circle"></i>
        <% end %>
      </div>

      <h5 class="card-title font-weight-bold mb-1"><%= review.title.capitalize %></h5>
      <p class="mb-0"><i class="far fa-envelope-open mr-2"></i><%= review.message %></p>
    </div>
  </div>
  <div class="reviewer d-flex align-items-end justify-content-end">
    <div class="reviewer-info d-flex flex-column align-items-end mr-3">
      <h5><%= renter.user.username.capitalize %></h5>
      <h6>Jacky member since <%= renter.user.created_at.strftime("%b %d") %></h6>
    </div>
    <% if renter.user.photo.attached? %>
      <%= cl_image_tag renter.user.photo.key, crop: :fill, class: 'profile-avatar' %>
    <% else %>
      <%= image_tag 'test.png', class: 'profile-avatar' %>
    <% end %>
  </div>

</div>