config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :profiles, only: [:show] do
    get '/cars', to: 'cars#current_user_cars', as: :cars
  end


  resources :cars do
    resources :rentals, only: [:new, :create]
    get '/rentals', to: 'rentals#current_car_rentals'
    resources :reviews, only: [:index, :show]
  end

  resources :rentals, only: [:index, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
  end


  # resources :reviews, only: [:index, :show]

    # resources :rentals, only: [:index, :new, :create, :show, :destroy] do
      # resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @car.photo.key %>');">
  <div class="container">
  </div>
</div>

app/views/shared/_form.html.erb
<h1> Rent your car </h1>
<p> Please fill your Car's Informations: </p>
<%= simple_form_for [@car] do |f|%>
        <%= f.input :brand, input_html: { class: "new-car-input" } %>
        <%= f.input :model, input_html: { class: "new-car-input" } %>
        <%= f.input :pick_up_address, input_html: { class: "new-car-input" } %>
        <%= f.input :pick_up_city, input_html: { class: "new-car-input" } %>
        <%= f.input :price_per_day, input_html: { class: "new-car-input" } %>
        <%= f.input :description, input_html: { class: "new-car-input" } %>
        <%= f.input :color, input_html: { class: "new-car-input" } %>
        <%= f.input :watts, input_html: { class: "new-car-input" } %>
        <%= f.input :rim_size, input_html: { class: "new-car-input" } %>
         <%= f.input :neon, as: :boolean, input_html: { class: "new-car-input" } %>
        <%= f.input :photo, as: :file %>
        <%= f.submit class:'btn btn-jacky btn-block' %>
      <% end %>

app/views/shared/_navbar.html.erb
<div class='background-navbar'>
  <div class="navbar d-flex">
    <%= link_to root_path do  %>
      <%= image_tag "logo-jackynb.png", alt: "alttext", class: 'logo center' %>
    <% end %>
    <div class="content d-flex pr-20">
      <div class="nav-item text-center mr-5 margin-top-navbar mb-0">
        <%= link_to cars_path do  %>
          <i class="fas fa-search"></i>
          <p class='mt-0'> Cars </p>
        <% end %>
      </div>
      <div class='nav-item text-center  mr-5 margin-top-navbar mb-0'>
        <%= link_to new_car_path do %>
          <i class='fas fa-plus'></i>
          <p class='mt-0'> Add a car</p>
        <% end %>
      </div>
      <div class="nav-item text-center margin-top-navbar mr-5">
        <% if current_user.nil? %>
          <%= link_to new_user_session_path do %>
            <i class="fas fa-angle-down"></i>
            <p class='mt-0'> My activity </p>
          <% end %>
        <% elsif policy(current_user).show? %>
          <%= link_to rentals_path do %>
          <i class="fas fa-angle-down"></i>
          <p class='mt-0'> My activity </p>
          <% end %>
        <% end %>
      </div>
      <div class='nav-item text-center profile-dropdown '>
        <% if current_user.nil? %>
          <%= link_to new_user_session_path do %>
            <div class='nav-icon'>
              <i class='far fa-user'></i>
              <p class='mt-0'> Login </p>
            </div>
          <% end %>
        <% elsif policy(current_user).show? %>
          <button class="btn dropdown-toggle pl-0" type="button" id="menu1" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
            <% if current_user.photo.attached?%>
              <%= cl_image_tag current_user.photo.key, class: 'avatar-large'%>
            <% else %>
              <i class='far fa-user avatar-large'></i>
            <% end %>
          </button>
          <div class="dropdown ">
            <div class="dropdown-menu dropdown-menu-right shadow-sm rounded mt-1" role="menu" aria-labelledby="menu1">
              <%= link_to "My profile",profile_path(current_user), class: 'dropdown-item'  %>
              <%= link_to "Update my informations", edit_user_registration_path, class: 'dropdown-item'  %>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>