config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :profiles, only: [:show] do
    get '/cars', to: 'cars#current_user_cars', as: :cars
  end


  resources :cars do
    resources :rentals, only: [:new, :create]
    get '/rentals', to: 'rentals#current_car_rentals'
    resources :reviews, only: [:index, :show]
  end

  resources :rentals, only: [:index, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
  end


  # resources :reviews, only: [:index, :show]

    # resources :rentals, only: [:index, :new, :create, :show, :destroy] do
      # resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :car
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :start_date, :end_date, presence: true

  def duration
    (self.end_date - self.start_date) / (60*60*24)
  end

  def days
    duration
    if duration.round > 1
      day = 'days'
    else
      day = 'day'
    end
    return "#{duration.round} #{day}"
  end

  def price
    duration
    (duration * self.car.price_per_day).round
  end

  def finished?
    self.end_date <= Time.zone.now
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :find_by_id, only: [:show, :destroy]

  def index
    @rentals = policy_scope(Rental)
  end

  def new
    @rental = Rental.new
    @car = Car.find(params[:car_id])
    authorize @rental
    authorize @car
  end

  def create
    @rental = Rental.new(set_rental_params)
    @rental.car = Car.find(params[:car_id])
    @rental.user = current_user
    authorize @rental
    if @rental.save
      redirect_to rentals_path
    else
      render :new
    end
  end

  def destroy
    # profil of renters and offers
    authorize @rental
    @rental.destroy
    redirect_to cars_path
  end

  def current_car_rentals
    @car = Car.find(params[:car_id])
    @rentals = @car.rentals
    # @rentals = policy_scope(Rental).where(car: @car)
    # authorize @rentals
    authorize @car

    # @rentals.each do |rental|
    #   authorize rental
    # end
    # @rentals = policy_scope(Rental)

  end

  private

  def find_by_id
    @rental = Rental.find(params[:id])
  end

  def set_rental_params
    params.require(:rental).permit(:car, :user, :start_date, :end_date)
  end

end

app/views/rentals/shared/_rentercard.html.erb
<div class="card mt-4 rentercard">
  <!-- <img src="#" alt="" style="border-radius: 50%; width: 50px; height: 50px; border: 1px solid grey;"> -->
  <div class="row no-gutters">
    <div class="col-4">
       <% if renter.user.photo.attached? %>
        <%= cl_image_tag renter.user.photo.key, crop: :fill, class: 'card-img' %>
      <% else %>
        <%= image_tag 'test.png', class: 'card-img' %>
      <% end %>
    </div>
    <div class="col-8 d-flex justify-content-between">
      <div class="card-body">
        <h5 class="card-title font-weight-bold"><%= renter.user.username.capitalize %><i class="fas fa-heart mx-3"></i>your <%= renter.car.model %></h5>
        <p><i class="far fa-calendar-alt mr-2"></i><%= renter.start_date.strftime("%b %d") %> - <%= renter.end_date.strftime("%b %d") %><i class="fas fa-euro-sign ml-5 mr-2"></i><%= renter.price %> (<%= renter.days %>)</p>
        <p><i class="far fa-envelope-open mr-2"></i><%= renter.user.email %><i class="fas fa-phone ml-5 mr-2"></i><%= renter.user.phone_number %></p>
        <p><i class="fas fa-map-marker-alt mr-2"></i><%= renter.car.pick_up_address %></p>
      </div>
      <%= link_to rental_path(renter), method: :delete, data: { confirm: "Are you sure?" }, class: 'text-decoration-none' do %>
        <i class="fas fa-times-circle"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/rentals/shared/_tripcard.html.erb
<div class="card mt-4 tripcard border-0 rounded shadow">
  <div class="row no-gutters">
    <div class="col-md-6 images">
      <%= cl_image_tag rental.car.photo.key, class: "card-img shadow" %>
      <% if rental.car.user.photo.attached? %>
        <%= cl_image_tag rental.car.user.photo.key, class: 'owner-avatar' %>
      <% else %>
        <%= image_tag 'test.png', class: 'owner-avatar-default' %>
      <% end %>
    </div>
    <div class="col-md-6 d-flex flex-column justify-content-between">

      <div class="card-body">
        <div class="first-line d-flex justify-content-between">
          <h5 class="card-title font-weight-bold mb-2"><%= Car.find(rental.car_id).model %></h5>
          <%= link_to rental_path(rental), method: :delete, data: { confirm: "Are you sure?" }, class: 'text-decoration-none' do %>
            <i class="fas fa-times-circle"></i>
          <% end %>
        </div>
        <div class="other-lines d-flex flex-column justify-content-start">
          <h6 class='mb-1'><i class="fas fa-euro-sign mr-2"></i><%= rental.price %> (<%= rental.days %>)</h6>
          <% if rental.end_date > Time.zone.now %>
            <p class='mb-1'><i class="fas fa-map-marker-alt mr-2"></i>
            <%=  Car.find(rental.car_id).pick_up_address %></p>
          <% end %>
          <p><i class="far fa-calendar-alt mr-2"></i>
          <%= rental.start_date.strftime("%b %d") %> - <%= rental.end_date.strftime("%b %d") %></p>
        </div>

        <div class="link-icons p-0 d-flex">
          <%= link_to 'Informations', car_path(rental.car_id), class: 'text-decoration-none btn btn-secondary btn-jacky' %>
          <%= link_to new_rental_review_path(rental), class: 'ml-1' do  %>
            <i class="far fa-comment-alt btn btn-secondary btn-review"></i>
          <% end %>
        </div>
      </div>



    </div>
  </div>
</div>
<!-- input_html: { type: 'button', toggle: "tooltip", placement: "top", title: "You haven't try it!" } -->