config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :profiles, only: [:show] do
    get '/cars', to: 'cars#current_user_cars', as: :cars
  end


  resources :cars do
    resources :rentals, only: [:new, :create]
    get '/rentals', to: 'rentals#current_car_rentals'
    resources :reviews, only: [:index, :show]
  end

  resources :rentals, only: [:index, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
  end


  # resources :reviews, only: [:index, :show]

    # resources :rentals, only: [:index, :new, :create, :show, :destroy] do
      # resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :rentals, dependent: :destroy
  has_many :reviews, through: :rentals

  validates :brand, :model, :pick_up_address, :price_per_day, presence: true
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  has_one_attached :photo
  validates :photo, presence: true

  def renter_reviews
    renter_reviews = []
    self.rentals.each do |rental|
      renter_review = rental.reviews.select { |review| review.review_type == "feedback_from_renter"}[0]
      unless renter_review.nil?
        renter_reviews << renter_review
      end
    end
    renter_reviews
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_car, only: [:show, :edit, :update, :destroy]

  def index
     @cars = policy_scope(Car)
     @search = params[:search]
    if params[:search].nil?
       @cars
    else
      @cars = @cars.select { |car| car.pick_up_city.downcase.include?(params[:search].downcase)}
    end
  end

  def show
    @rental = Rental.new
    @rental.car = @car
    @rental.user = current_user
    authorize @car
    @car_reviews = []
    @rentals = @car.rentals
    @rentals.each { |rental|  rental.reviews.each { |review| @car_reviews << review }  }

  end

  def new
    @car = Car.new
    authorize @car
  end

  def create

    @car = Car.new(set_cars_params)
    authorize @car
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit
    authorize @car
  end

  def update
    authorize @car
    if @car.update(set_cars_params)
      redirect_to cars_path
    else
      render :edit
    end

  end

  def destroy
    authorize @car
    @car.destroy
    redirect_to cars_path
  end

  def current_user_cars
    @cars = policy_scope(Car).select { |car| car.user_id == current_user.id }

    # @cars = Car.select { |car| car.user_id == current_user.id }
    # @cars.each {|car| authorize car }
  end

  private

  def find_car
    @car = Car.find(params[:id])
  end

  def set_cars_params
    params.require(:car).permit(:brand, :model, :pick_up_address, :pick_up_city, :price_per_day, :description, :photo)
  end

end

app/views/cars/current_user_cars.html.erb
<div class="container my-5">
  <h1>All your cars</h1>
  <div class="row">
    <% @cars.each do |car| %>
      <div class="card col-4 m-4" style="width: 18rem; max-height: 30rem;">
        <%= cl_image_tag car.photo.key, crop: :fill, class: "card-img-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= car.brand %> - <%= car.model %> </h5>
          <p class="card-text"> <%= car.description %> </p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"> address : <%= car.pick_up_address %> </li>
          <li class="list-group-item"> <%= car.price_per_day %> € </li>
        </ul>
        <% if policy(car).edit? && policy(car).destroy? %>
          <p><%= link_to 'Edit here',edit_car_path(car), class: 'text-decoration-none' %> | <%= link_to 'Delete here',car_path(car), method: :delete, data: { confirm: "Are you sure?" }, class: 'text-decoration-none'%></p>
        <% end %>
        <% if policy(car).current_car_rentals? %>
          <%= link_to 'Rentals', car_rentals_path(car), class: 'text-decoration-none' %>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= link_to "Back to profile", profile_path(current_user), class: "text-decoration-none" %>
</div>

app/views/cars/edit.html.erb
<div class="container justify-content-center">
  <h1>Create a tuning car! </h1>
  <div class="col-6">
    <%= render 'shared/form' %>
  </div>
</div>

app/views/cars/index.html.erb
<div class='d-flex'>
  <div class='d-flex flex-column align-items-center sticky-map-search'>
    <div class='search-index mt-4'>
      <form action="/cars" method="get" class='form-inline md-form mr-auto mb-4'>
        <div class="form-group d-flex ">
          <input type="text" name='search' placeholder="City" class='form-control-search mr-sm-2 w-100 shadow'>
        </div>
        <input type="date" class='form-control-search mr-sm-2 shadow' name="start_date">
        <input type="date" class='form-control-search mr-sm-2 shadow' name="end_date" >
        <button type="submit" class= 'btn btn-jacky pt-50 pl-20'><i class="fa fa-search"></i></button>
      </form>
    </div>
    <div id="map" class="mt-4"></div>
  </div>

  <div class='index'>
    <div class="container">
     <div class='title-div pt-4'>
        <h2 class='title-all-cars'></h2>
      </div>

      <div>
        <div class='cards'>
          <% @cars.each do |car| %>
            <div class='card-index new-car-card'>
              <%= link_to (car_path(car))  do %>
                <% if car.photo.attached? %>
                  <%= cl_image_tag car.photo.key, crop: :fill, class: 'image-index' %>
                <% else %>
                  <img class="image-index" src="..." alt="No image yet">
                <% end %>

                <p class='btn btn-jacky more-details'>More info </p>
                <div class='text-center content-card-index w-100'>
                  <h5 class="car-brand-title mb-2"><%= car.brand %> - <%= car.model %> </h5>
                  <div class='d-flex justify-content-between mr-5 ml-5'>
                    <p class='pick-up-city-title'><%= car.pick_up_city %> </p>
                    <p class='pick-up-address'><%= car.pick_up_address %> </p>
                    <p class='price-text'> <strong> <%= car.price_per_day %> €/day </strong></p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
  <div class="new-car-form">
    <div class="container justify-content-center">
      <%= render 'shared/form' %>
    </div>
  </div>

app/views/cars/show.html.erb
<!-- <div class='jackynb-background'>
  <div class="container mt-5">
    <div class="row">
      <div class="col-7">
        <div class="card-body-large shadow-sm p-3 mb-3 bg-white rounded">
          <h5 class="card-title-index pl-3 pr-3"> <%= @car.brand %> - <%= @car.model %> </h5>
          <div class="d-flex pl-3 pr-3">
            <i class="fas fa-map-pin mr-2 mb-3"></i>
            <p class="card-text "> <%= @car.pick_up_city %> </p>

          </div>
          <p class="card-text border-top pt-2 pl-3 pr-3"> <%= @car.description %> </p>
          <div class="card-text border-top border-bottom pt-2 mb-2">
            <p class="card-text pl-3 pr-3"><strong> Attributes </strong></p>
            <div class= 'd-flex justify-content-around mt-4' >
              <div class="text-center">
                <i class="fas fa-paint-roller fa-lg"></i>
                <p class="p-10 font-italic"> <%= @car.color %> </p>
              </div>
              <div class="text-center">
                <i class="fas fa-euro-sign fa-lg"></i>
                <p class="p-10 font-italic"> <%= @car.price_per_day %> </p>
              </div>
              <div class="text-center">
                <i class="fas fa-lightbulb fa-lg"></i>
                <p class="p-10 font-italic"> <%#= @car.neon ? "Yes" : "No" %> </p>
              </div> -->

<div class="container">
  <%= link_to "Back to Home", cars_path, class: 'btn btn-light mt-2' %>
  <div class="row">
    <div class="col-7">
      <div class="card-body-large show-card p-3 mt-3 mb-3">
        <div class=" d-flex justify-content-between ">
          <h5 class="card-title card-title-index m-0">
            <%= @car.brand %> - <%= @car.model %>
          </h5>
          <p class="card-text card-city">
            <i class="fas fa-map-pin"></i> <%= @car.pick_up_city %>
          </p>
        </div>
        <div class="car-picture">
          <% if @car.photo.attached? %>
            <%= cl_image_tag @car.photo.key, crop: :fill, class: 'w-100' %>
          <% else %>
            <img class="w-100" src="..." alt="No image yet">
          <% end %>
        </div>

        <p class="card-text mt-3"> <%= @car.description %> </p>

        <hr>

        <div class='card-text d-flex justify-content-between mt-4 text-center' >
          <div>
            <i class="icon fas fa-paint-roller fa-lg"></i>
            <p class="icon-text "> <%= @car.color %> </p>
          </div>
          <div>
            <i class="icon fas fa-euro-sign fa-lg"></i>
            <p class="icon-text "> <%= @car.price_per_day %> </p>
          </div>
          <div>
            <i class="icon fas fa-lightbulb fa-lg"></i>
            <p class="icon-text "> <%= @car.neon ? "Yes" : "No" %> </p>
          </div>
          <div>
            <i class="icon fas fa-volume-up fa-lg"></i>
            <p class="icon-text "> <%= @car.watts %> watts </p>
          </div>
          <div>
            <i class="icon fas fa-truck-monster fa-lg"></i>
            <p class="icon-text "> <%= @car.rim_size %> '' </p>
          </div>
          <div>
            <i class="icon fas fa-user fa-lg"></i>
            <p class="icon-text "> <%= @car.user.username %> </p>
          </div>
        </div>
        <div class="btns mt-3">
          <% if policy(@car).edit? %>
            <%= link_to 'Edit here',edit_car_path(@car), class: 'btn btn-jacky'%>
          <% end %>
          <% if policy(@car).destroy? %>
            <%= link_to 'Delete here',car_path(@car), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-jacky' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-5">
      <div class="card-body-large p-3 mb-5 bg-transparent rounded">
        <div class="new-rent-form">
          <div class="container justify-content-center">
            <h5 class="card-title-index pl-3 pr-3"> <%= "Rent the #{@car.brand} - #{@car.model}" %> </h5>
            <%= simple_form_for [@car, @rental] do |f| %>
              <%= f.input :start_date, as: :string, required: false, input_html: {class: "new-rent-input datepicker"} %>
              <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker new-rent-input "} %>
              <%= f.button :submit, "Rent this beauty now", class: "btn btn-jacky w-75" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% unless @car_reviews.empty? %>
    <div class="card-body-large card-review shadow-sm p-3 mb-3">
      <h1>Comments</h1>
      <% @car_reviews.each do |review| %>
        <div class="card mb-2">
          <div class="card-header comment-card">
            <% star = '<i class="fas fa-star text-warning"></i>' %>
            <%= (star * review.rating).html_safe %>
          </div>
          <div class="card-body card-review">
            <h5 class="card-review"> <%= "#{review.title}" %> </h5>
            <p class="card-review"> <%= "#{review.message}" %> </p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>